spring:
  application:
    name: cassandra

spring.cassandra:
  keyspace-name: example
  schema-action: recreate
  local-datacenter: datacenter1

management:
  tracing:
    sampling:
      probability: 1.0

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
