{
 "title": "Greetings",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Greetings by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gr/s" } },
   "targets": [
    {
     "expr": "sum(rate(greeting_seconds_count[1m])) by (greeting_name)",
     "legendFormat": "{{greeting_name}}"
    }
   ]
  },
  {
   "title": "Greetings by Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gr/s" } },
   "targets": [
    {
     "expr": "sum((rate(greeting_greeted_total[1m])))",
     "legendFormat": "greeted"
    },
    {
     "expr": "sum((rate(greeting_failed_total[1m])))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Greetings Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(greeting_seconds_bucket[1m])) by (le))",
     "legendFormat": "TP95"
    },
    { "expr": "max(greeting_seconds_max)", "legendFormat": "max" }
   ]
  },
  {
   "title": "Greetings Latency Histogram",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(greeting_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}