version: '3'
services:
    cassandra:
        container_name: cassandra
        image: cassandra:3.11.10
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        ports:
            - 7000:7000
            - 9042:9042
