spring:
  application:
    name: stream-producer

spring.cloud.stream:
  source: channel
  bindings.channel-out-0:
    destination: channeldestination
    group: channelgroup

management:
  tracing:
    sampling:
      probability: 1.0
