# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Brave

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

#    - name: Clone the projects
#      run: ./scripts/build_all_projects_locally.sh
    - name: Execute Gradle build with Brave
      run: ./gradlew -Pbrave acceptanceTest --rerun-tasks
